In [2]:
# Importamos todas las librerías necesarias
import pandas as pd
import numpy as np

In [2]:
# Leemos el dataset
df = pd.read_csv('DatasetFusionadoCompuesto.csv')
df.head()

Grupo   Año               TIempo      Session    Objeto  Accion  \
0  DBA 1516 P2 GA  1516  22/10/2015 17:29:21  84557317827  PROBLEM1      20   
1  DBA 1516 P2 GA  1516  22/10/2015 17:29:22  84557317827  PROBLEM1      40   
2  DBA 1516 P2 GA  1516  22/10/2015 17:29:39  84557317827  PROBLEM1      60   
3  DBA 1516 P2 GA  1516  22/10/2015 17:34:09  13090455475  PROBLEM1      20   
4  DBA 1516 P2 GA  1516  22/10/2015 17:34:10  13090455475  PROBLEM1      40   

  Nota    Compuesto  Unnamed: 8  Unnamed: 9  Unnamed: 10 Unnamed: 11  \
0  7,8  PROBLEM1-20         NaN         NaN          NaN         NaN   
1  7,8  PROBLEM1-40         NaN         NaN          NaN         NaN   
2  7,8  PROBLEM1-60         NaN         NaN          NaN         NaN   
3  7,8  PROBLEM1-20         NaN         NaN          NaN         NaN   
4  7,8  PROBLEM1-40         NaN         NaN          NaN         NaN   

   Unnamed: 12  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN

In [3]:
# Eliminamos las columnas con valores NaN
df=df.dropna(axis=1)
df.head()

Grupo   Año               TIempo      Session    Objeto  Accion  \
0  DBA 1516 P2 GA  1516  22/10/2015 17:29:21  84557317827  PROBLEM1      20   
1  DBA 1516 P2 GA  1516  22/10/2015 17:29:22  84557317827  PROBLEM1      40   
2  DBA 1516 P2 GA  1516  22/10/2015 17:29:39  84557317827  PROBLEM1      60   
3  DBA 1516 P2 GA  1516  22/10/2015 17:34:09  13090455475  PROBLEM1      20   
4  DBA 1516 P2 GA  1516  22/10/2015 17:34:10  13090455475  PROBLEM1      40   

  Nota    Compuesto  
0  7,8  PROBLEM1-20  
1  7,8  PROBLEM1-40  
2  7,8  PROBLEM1-60  
3  7,8  PROBLEM1-20  
4  7,8  PROBLEM1-40

In [4]:
# Ordenamos los valores según las sesiones
df.sort_values(by="Session")
df.head()

Grupo   Año               TIempo      Session    Objeto  Accion  \
0  DBA 1516 P2 GA  1516  22/10/2015 17:29:21  84557317827  PROBLEM1      20   
1  DBA 1516 P2 GA  1516  22/10/2015 17:29:22  84557317827  PROBLEM1      40   
2  DBA 1516 P2 GA  1516  22/10/2015 17:29:39  84557317827  PROBLEM1      60   
3  DBA 1516 P2 GA  1516  22/10/2015 17:34:09  13090455475  PROBLEM1      20   
4  DBA 1516 P2 GA  1516  22/10/2015 17:34:10  13090455475  PROBLEM1      40   

  Nota    Compuesto  
0  7,8  PROBLEM1-20  
1  7,8  PROBLEM1-40  
2  7,8  PROBLEM1-60  
3  7,8  PROBLEM1-20  
4  7,8  PROBLEM1-40

In [5]:
# Filtrado dataset
# Grupo DBA 1516 P2 GA
newdf = df[(df.Grupo == "DBA 1516 P2 GA")]
newdf.head()

Grupo   Año               TIempo      Session    Objeto  Accion  \
0  DBA 1516 P2 GA  1516  22/10/2015 17:29:21  84557317827  PROBLEM1      20   
1  DBA 1516 P2 GA  1516  22/10/2015 17:29:22  84557317827  PROBLEM1      40   
2  DBA 1516 P2 GA  1516  22/10/2015 17:29:39  84557317827  PROBLEM1      60   
3  DBA 1516 P2 GA  1516  22/10/2015 17:34:09  13090455475  PROBLEM1      20   
4  DBA 1516 P2 GA  1516  22/10/2015 17:34:10  13090455475  PROBLEM1      40   

  Nota    Compuesto  
0  7,8  PROBLEM1-20  
1  7,8  PROBLEM1-40  
2  7,8  PROBLEM1-60  
3  7,8  PROBLEM1-20  
4  7,8  PROBLEM1-40

In [6]:
newdf.tail()

Grupo   Año               TIempo      Session    Objeto  \
1586  DBA 1516 P2 GA  1516  23/11/2015 16:56:30  19073721848  PROBLEM9   
1587  DBA 1516 P2 GA  1516  23/11/2015 16:56:39  19073721848  PROBLEM9   
1588  DBA 1516 P2 GA  1516  23/11/2015 17:36:57  22645031532  PROBLEM9   
1589  DBA 1516 P2 GA  1516  23/11/2015 17:36:58  22645031532  PROBLEM9   
1590  DBA 1516 P2 GA  1516  23/11/2015 17:37:05  22645031532  PROBLEM9   

      Accion Nota    Compuesto  
1586      40  7,8  PROBLEM9-40  
1587      60  7,8  PROBLEM9-60  
1588      20  7,8  PROBLEM9-20  
1589      40  7,8  PROBLEM9-40  
1590      60  7,8  PROBLEM9-60

In [7]:
# Cálculo del número de nodos
num = newdf['Compuesto'].nunique() + 2
print("Número de nodos",num)

Número de nodos 45


In [8]:
# Creamos una matriz de adyacencia vacía
adj_matrix = []
for i in range(num):
    new_row = []
    for j in range(num):
        new_row.append(0)
    adj_matrix.append(new_row)

In [9]:
# Obtenemos todos los posibles valores de la columna Compuesto y los ordenamos
labels = newdf['Compuesto'].unique().tolist()
labels.append('START')
labels.append('END')
print(labels)

['PROBLEM1-20', 'PROBLEM1-40', 'PROBLEM1-60', 'PROBLEM1-80', 'PROBLEM1-100', 'PROBLEM2-20', 'PROBLEM2-40', 'PROBLEM2-80', 'PROBLEM2-60', 'PROBLEM3-20', 'PROBLEM3-40', 'PROBLEM4-20', 'PROBLEM4-40', 'PROBLEM5-20', 'PROBLEM5-40', 'PROBLEM5-80', 'PROBLEM5-60', 'PROBLEM5-100', 'PROBLEM6-20', 'PROBLEM6-40', 'PROBLEM6-60', 'PROBLEM6-80', 'PROBLEM6-100', 'PROBLEM7-20', 'PROBLEM7-40', 'PROBLEM7-60', 'PROBLEM8-20', 'PROBLEM8-40', 'PROBLEM8-60', 'PROBLEM9-20', 'PROBLEM9-40', 'PROBLEM9-60', 'PROBLEM3-60', 'PROBLEM4-60', 'PROBLEM2-100', 'PROBLEM3-80', 'PROBLEM3-100', 'PROBLEM4-80', 'PROBLEM4-100', 'PROBLEM7-80', 'PROBLEM7-100', 'PROBLEM8-80', 'PROBLEM8-100', 'START', 'END']


In [10]:
# Crear diccionario entre labels y posiciones dentro de la lista de labels
diccionario = {}

# Iterar sobre la lista
for indice, elemento in enumerate(labels):
    # Agregar la clave-valor al diccionario
    diccionario[elemento] = indice

# Imprimir el diccionario resultante
print(diccionario)

{'PROBLEM1-20': 0, 'PROBLEM1-40': 1, 'PROBLEM1-60': 2, 'PROBLEM1-80': 3, 'PROBLEM1-100': 4, 'PROBLEM2-20': 5, 'PROBLEM2-40': 6, 'PROBLEM2-80': 7, 'PROBLEM2-60': 8, 'PROBLEM3-20': 9, 'PROBLEM3-40': 10, 'PROBLEM4-20': 11, 'PROBLEM4-40': 12, 'PROBLEM5-20': 13, 'PROBLEM5-40': 14, 'PROBLEM5-80': 15, 'PROBLEM5-60': 16, 'PROBLEM5-100': 17, 'PROBLEM6-20': 18, 'PROBLEM6-40': 19, 'PROBLEM6-60': 20, 'PROBLEM6-80': 21, 'PROBLEM6-100': 22, 'PROBLEM7-20': 23, 'PROBLEM7-40': 24, 'PROBLEM7-60': 25, 'PROBLEM8-20': 26, 'PROBLEM8-40': 27, 'PROBLEM8-60': 28, 'PROBLEM9-20': 29, 'PROBLEM9-40': 30, 'PROBLEM9-60': 31, 'PROBLEM3-60': 32, 'PROBLEM4-60': 33, 'PROBLEM2-100': 34, 'PROBLEM3-80': 35, 'PROBLEM3-100': 36, 'PROBLEM4-80': 37, 'PROBLEM4-100': 38, 'PROBLEM7-80': 39, 'PROBLEM7-100': 40, 'PROBLEM8-80': 41, 'PROBLEM8-100': 42, 'START': 43, 'END': 44}


In [11]:
# Cálculo de la matriz de frecuencias
last_session = -1
last_label = 'last_label'
for index, row in newdf.iterrows():
    new_session = row['Session']
    new_label = row['Compuesto']
    if (new_session == last_session):
        # Añadir una transición del último label al label actual
        adj_matrix[diccionario[last_label]][diccionario[new_label]] += 1
    else:
        if (last_session != -1):
            # Añadir una transición del último label a END
            adj_matrix[diccionario[last_label]][diccionario['END']] += 1
        # Añadir una transición de START al label actual
        adj_matrix[diccionario['START']][diccionario[new_label]] += 1
    last_session = new_session
    last_label = new_label

In [12]:
# Imprimimos la matriz resultante
print(np.matrix(adj_matrix))

[[  0 228   0 ...   0   0 397]
 [  0   0  23 ...   0   0 118]
 [  0   0   0 ...   0   0  24]
 ...
 [  0   0   0 ...   0   0   1]
 [628   2   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]


In [13]:
# Grupos en df
grupos = df['Grupo'].unique().tolist()

In [14]:
import numpy as np

# Creamos una matriz de ejemplo de 5x5
matriz = np.array([[1, 2, 3, 4, 5],
                   [6, 7, 8, 9, 10],
                   [11, 12, 13, 14, 15],
                   [16, 17, 18, 19, 20],
                   [21, 22, 23, 24, 25]])

# Obtenemos el número total de elementos en la matriz
num_elem = matriz.size

# Ordenamos los elementos de mayor a menor y los aplanamos en un array unidimensional
elementos_ordenados = np.sort(matriz.flatten())[::-1]

# Calculamos la suma acumulada de las frecuencias y la normalizamos
frecuencias_acumuladas = np.cumsum(elementos_ordenados) / np.sum(elementos_ordenados)

# Encontramos el índice donde se encuentra el 90% de las frecuencias más altas
indice_corte = np.argmax(frecuencias_acumuladas >= 0.9)

# Hacemos cero a todos los elementos que estén por debajo del corte
matriz[matriz < elementos_ordenados[indice_corte]] = 0

# Imprimimos la matriz resultante
print(matriz)

[[ 0  0  0  0  0]
 [ 0  0  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [15]:
# Leemos el dataset
df = pd.read_csv('MaribelDataset15-21.csv')

# Eliminamos las columnas con valores NaN
df=df.dropna(axis=1)

# Ordenamos los valores según las sesiones
df.sort_values(by="Session")

Grupo   Year                sTime                  Session  \
75806  DBA 2122 P2 GA  Y2021  21/11/2021 20:31:10  101 Batallion1016890566   
75316  DBA 2122 P2 GA  Y2021  01/11/2021 18:32:22  101 Batallion1053384352   
75315  DBA 2122 P2 GA  Y2021  01/11/2021 18:32:22  101 Batallion1053384352   
75789  DBA 2122 P2 GA  Y2021  15/11/2021 23:46:33  101 Batallion1096397903   
75686  DBA 2122 P2 GA  Y2021  13/11/2021 19:06:04  101 Batallion1104968492   
...               ...    ...                  ...                      ...   
74939  DBA 2021 P2 GM  Y2020  03/11/2020 20:24:34     Telefonica9958588142   
74940  DBA 2021 P2 GM  Y2020  03/11/2020 20:24:34     Telefonica9958588142   
74941  DBA 2021 P2 GM  Y2020  03/11/2020 20:24:34     Telefonica9958588142   
74942  DBA 2021 P2 GM  Y2020  03/11/2020 20:24:35     Telefonica9958588142   
74943  DBA 2021 P2 GM  Y2020  03/11/2020 20:24:39     Telefonica9958588142   

      Problem  Milestone  Valid        bad                              bad.1  \
75806      P7         40      1  Y20Y42071  DBA 1819 P2 GBBellatrix9715471439   
75316      P2         40      1  Y20Y41581  DBA 1819 P2 GBBellatrix9715470949   
75315      P2         20      1  Y20Y41580  DBA 1819 P2 GBBellatrix9715470948   
75789      P2         20      1  Y20Y42054  DBA 1819 P2 GBBellatrix9715471422   
75686      P7         40      1  Y20Y41951  DBA 1819 P2 GBBellatrix9715471319   
...       ...        ...    ...        ...                                ...   
74939      P8         20      1  Y20Y41204  DBA 1819 P2 GBBellatrix9715470572   
74940      P8         40      1  Y20Y41205  DBA 1819 P2 GBBellatrix9715470573   
74941      P8         60      1  Y20Y41206  DBA 1819 P2 GBBellatrix9715470574   
74942      P8         60      1  Y20Y41207  DBA 1819 P2 GBBellatrix9715470575   
74943      P8        100      1  Y20Y41208  DBA 1819 P2 GBBellatrix9715470576   

        bad.2  bad.3  bad.4       Time  sessionTime  
75806  P42070      1      1  259533070            0  
75316  P41580      1      1  257797942            0  
75315  P41579      1      1  257797942            0  
75789  P42053      1      1  259026393            0  
75686  P41950      1      1  258836764  100,9999997  
...       ...    ...    ...        ...          ...  
74939  P41203      1      1  226441474  4,999999912  
74940  P41204      1      1  226441474  4,999999912  
74941  P41205      1      1  226441474  4,999999912  
74942  P41206      1      1  226441475  4,999999912  
74943  P41207      1      1  226441479  4,999999912  

[87030 rows x 14 columns]

In [24]:
df['Problem'] = df['Problem'].replace({'P':''}, regex=True)
df['Compuesto'] = 'PROBLEM' + df.Problem.apply(str) + '-' + df.Milestone.apply(str)
df['Compuesto']

0        PROBLEMA1-20
1        PROBLEMA1-40
2        PROBLEMA1-60
3        PROBLEMA1-20
4        PROBLEMA1-40
             ...     
87025    PROBLEMA6-20
87026    PROBLEMA6-40
87027    PROBLEMA6-20
87028    PROBLEMA6-40
87029    PROBLEMA6-40
Name: Compuesto, Length: 87030, dtype: object

In [6]:
matriz = np.array([[1, 2, 0], [0, 0, 0], [4, 5, 0], [0, 0, 0], [7, 8, 0]])
print(matriz)

[[1 2 0]
 [0 0 0]
 [4 5 0]
 [0 0 0]
 [7 8 0]]


In [7]:
columnas_a_mantener = ~np.all(matriz == 0, axis=0)
matriz_sin_columnas_de_ceros = matriz[:, columnas_a_mantener]
print(matriz_sin_columnas_de_ceros)

[[1 2]
 [0 0]
 [4 5]
 [0 0]
 [7 8]]


In [8]:
filas_a_mantener = ~np.all(matriz_sin_columnas_de_ceros == 0, axis=1)
matriz_final = matriz_sin_columnas_de_ceros[filas_a_mantener, :]
print(matriz_final)

[[1 2]
 [4 5]
 [7 8]]
